#!/usr/bin/env python3
"""
Regenerates the data feeding the "DFS Feedback Board" artifact
(https://claude.ai/code/artifact/467c254b-6a37-4244-8fdb-5a88ee24b927) directly
from the CSV snapshots in this folder, so the board is never hand-typed.

Source of truth: the most recent dated CSV in each subfolder —
  external_support_history/feedback_tracker/YYYY-MM-DD__Feedback_Tracker.csv
  external_support_history/weekly_ids/YYYY-MM-DD__Weekly_IDS_DFS_x_Singular_x_Cobalt.csv
(both are snapshots of Cobalt's live Google Sheets — see the folder's README.md
for how/when to add a new dated snapshot.)

Usage:
    python build_board_data.py

Output:
    external_support_history/generated/board_data.js
    — two consts, FEEDBACK_ROWS and IDS_ROWS, in the exact shape the artifact's
    <script> expects. Splice this file's contents into the artifact HTML
    (replacing the `const FEEDBACK_ROWS = [...]` / `const IDS_ROWS = [...]`
    lines) and republish. This script does not touch the artifact itself —
    it only regenerates the data feeding it.
"""
import csv
import glob
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
FEEDBACK_DIR = os.path.join(ROOT, "feedback_tracker")
IDS_DIR = os.path.join(ROOT, "weekly_ids")
OUT_DIR = os.path.join(ROOT, "generated")

FEEDBACK_COLS = [
    "#", "Short Name", "Full Description", "Report Date", "Owner", "Priority",
    "Status", "Source", "Singular Dev", "Solved Date", "Diagnostic", "Solution",
    "Story", "Singular Story", "Comments/Next Steps",
]
IDS_COLS = [
    "Status", "Priority", "Item to discuss", "Next Step", "Reported Date",
    "From", "Deadline", "Owner", "Comments",
]


def latest_snapshot(directory, name_fragment):
    pattern = os.path.join(directory, f"*__{name_fragment}.csv")
    matches = sorted(glob.glob(pattern))
    if not matches:
        raise SystemExit(f"No snapshot found matching {pattern}")
    return matches[-1]  # date-prefixed filenames sort chronologically


def clean_cell(v):
    v = (v or "").strip()
    if not v:
        return None
    # A handful of cells in the source Google Sheet have a curly apostrophe
    # (') that got mangled into the Unicode replacement character (U+FFFD)
    # at some point upstream, before this ever reaches us — repair it to a
    # plain apostrophe rather than shipping a broken glyph to the board.
    v = v.replace("�", "'")
    return v


def parse_number_id(v):
    if v is None:
        return None
    try:
        return float(v)
    except ValueError:
        return v


def load_rows(path, cols, id_col=None):
    with open(path, newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        rows = []
        for raw in reader:
            row = {}
            has_content = False
            for col in cols:
                val = clean_cell(raw.get(col))
                if col == id_col:
                    val = parse_number_id(val)
                row[col] = val
                if val is not None:
                    has_content = True
            if has_content:
                rows.append(row)
        return rows


def main():
    os.makedirs(OUT_DIR, exist_ok=True)

    feedback_path = latest_snapshot(FEEDBACK_DIR, "Feedback_Tracker")
    ids_path = latest_snapshot(IDS_DIR, "Weekly_IDS_DFS_x_Singular_x_Cobalt")

    feedback_rows = load_rows(feedback_path, FEEDBACK_COLS, id_col="#")
    ids_rows = load_rows(ids_path, IDS_COLS)

    date_tag = re.match(r"(\d{4}-\d{2}-\d{2})", os.path.basename(feedback_path)).group(1)

    out_path = os.path.join(OUT_DIR, "board_data.js")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(f"// AUTO-GENERATED by external_support_history/scripts/build_board_data.py\n")
        f.write(f"// Source snapshots: {os.path.basename(feedback_path)}, {os.path.basename(ids_path)}\n")
        f.write(f"// Do not hand-edit — re-run the script after adding a newer dated snapshot.\n")
        f.write("const FEEDBACK_ROWS = " + json.dumps(feedback_rows, ensure_ascii=False, indent=2) + ";\n\n")
        f.write("const IDS_ROWS = " + json.dumps(ids_rows, ensure_ascii=False, indent=2) + ";\n")

    print(f"Feedback Tracker: {len(feedback_rows)} rows from {os.path.basename(feedback_path)}")
    print(f"Weekly IDS:       {len(ids_rows)} rows from {os.path.basename(ids_path)}")
    print(f"Written to {out_path}")
    print(f"Source date tag: {date_tag}")


if __name__ == "__main__":
    main()
