import React, { useState, useCallback, useMemo, useRef, useEffect } from 'react';
import {
  initializeBlock,
  useBase,
  useRecords,
  useCustomProperties,
  useColorScheme,
} from '@airtable/blocks/interface/ui';
import type { Table, Field } from '@airtable/blocks/interface/models';
import {
  CaretDown as CaretDownIcon,
  CaretLeft as CaretLeftIcon,
  CaretRight as CaretRightIcon,
  CalendarBlank as CalendarBlankIcon,
  MagnifyingGlass as MagnifyingGlassIcon,
  X as XIcon,
  WarningCircle as WarningCircleIcon,
} from '@phosphor-icons/react';

// ─── Dark mode ────────────────────────────────────────────────────────────────
function useTheme(): 'light' | 'dark' {
  // Reads Airtable's own light/dark preference, not the OS/browser setting.
  const { colorScheme } = useColorScheme();
  useEffect(() => {
    const root = document.documentElement;
    if (colorScheme === 'dark') root.classList.add('dark'); else root.classList.remove('dark');
  }, [colorScheme]);
  return colorScheme;
}

// ─── Constants — DF Clients (tblLLUlDgJ4ktzF7c) ───────────────────────────────
const FIELD_IDS = {
  CLIENT_FULL_NAME:             'fldB3Wyam01D3wR5Q',
  CLIENT_DUE_DATE:              'fldnhs2n4z2EdZK9N',
  CLIENT_ITEMS_SOLD:            'fldEStULoGtNIjxPO',
  CLIENT_GOWN_NAME:             'fldJvr5mNgwmhfBlv',
  // Items Sold and Gown are both lookups (via shopify_order) of Orders -
  // Shopify's "Items" field, which is itself a multipleRecordLinks field —
  // not text. Their raw cell values are nested link structures, so they
  // must go through unwrapLinkedNames() below, not getCellValueAsString().
  CLIENT_ITEM_CATEGORY:         'fldE4AX5gz8pwah4j', // lookup chain terminating in a singleSelect — getCellValueAsString works directly
  CLIENT_DRESS_CREATION_YEAR:   'fldwgDZDs2CNEqPsQ', // number, precision 0 — created in sandbox appMmEE4zyHMGhkkd
  CLIENT_WEDDING_DATE:          'fldbgknumKGS5W5WU',
  CLIENT_CALLIGRAPHY_CARD_SENT: 'fldsBLLXkKPgqlN2e',
  CLIENT_CALLIGRAPHY_CARD_COMMENTS: 'fldfrtzC0BxWggmoU', // long text, created in sandbox appMmEE4zyHMGhkkd — Margo's name-variation notes for the card
} as const;

// ─── Date helpers ──────────────────────────────────────────────────────────────
function formatDate(value: string | null | undefined): string {
  if (!value) return '—';
  const d = new Date(value);
  if (isNaN(d.getTime())) return '—';
  return new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric' }).format(d);
}
function getLocalDateString(d: Date): string {
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
}
function getTodayLocalString(): string {
  return getLocalDateString(new Date());
}

// ─── Qualification floor (always-on, not a UI toggle) ──────────────────────────
// A client only ever belongs on this list if Item Category (fldE4AX5gz8pwah4j)
// contains at least one category that is NOT shoes or veil. Approved
// deviation from the original AC, since the physical card is generated by a
// separate process and this page only tracks status for clients who
// actually have a qualifying item.
// An EMPTY Item Category (no orders at all, so nothing to categorize) is
// NOT excluded here — that's controlled by the visible "Items Sold" filter
// below instead (default: hidden), so the user can choose to see those
// clients rather than have them silently disappear from this hard floor.
const EXCLUDED_ONLY_ITEM_CATEGORIES = ['shoes', 'veil'];
function qualifiesNotOnlyShoesOrVeil(categoryNames: string[]): boolean {
  if (categoryNames.length === 0) return true;
  return categoryNames.some(name => !EXCLUDED_ONLY_ITEM_CATEGORIES.includes(name.trim().toLowerCase()));
}

// ─── Nested-lookup unwrapping ──────────────────────────────────────────────────
// Items Sold and Gown are lookups of a multipleRecordLinks field ("Items" on
// Orders - Shopify), not a text/formula field — their raw cell value is an
// array of per-linked-record entries, each of which may itself be a plain
// string, or an object shaped like { linkedRecordId, value } whose `value` is
// the resolved linked-record name(s) (or another nested array/object, for a
// lookup chain more than one hop deep). getCellValueAsString does not reliably
// flatten this in this runtime (same underlying quirk BRANDING.md §9 and
// did_not_convert.tsx's unwrapLookupString document) — recurse and collect
// every `name`/string found instead of assuming a fixed shape.
function unwrapLinkedNames(value: unknown): string[] {
  if (value == null) return [];
  if (typeof value === 'string') return value.trim() ? [value.trim()] : [];
  if (Array.isArray(value)) return value.flatMap(unwrapLinkedNames);
  if (typeof value === 'object') {
    const obj = value as Record<string, unknown>;
    if (typeof obj.name === 'string') return obj.name.trim() ? [obj.name.trim()] : [];
    if ('value' in obj) return unwrapLinkedNames(obj.value);
    return Object.values(obj).flatMap(unwrapLinkedNames);
  }
  return [];
}
function getLinkedNamesDisplay(value: unknown): string {
  return unwrapLinkedNames(value).join(', ');
}

// ─── Calendar utilities ────────────────────────────────────────────────────────
const MONTHS_EN = ['January','February','March','April','May','June','July','August','September','October','November','December'];
const DAYS_EN = ['MO','TU','WE','TH','FR','SA','SU'];
function getCalendarDays(year: number, month: number): Date[] {
  const first = new Date(year, month, 1);
  const startOffset = (first.getDay() + 6) % 7; // Monday-start
  const start = new Date(year, month, 1 - startOffset);
  return Array.from({ length: 42 }, (_, i) => new Date(start.getFullYear(), start.getMonth(), start.getDate() + i));
}
function isSameDay(a: Date, b: Date): boolean {
  return a.getFullYear() === b.getFullYear() && a.getMonth() === b.getMonth() && a.getDate() === b.getDate();
}

// ─── CalendarPopup ──────────────────────────────────────────────────────────────
interface CalendarPopupProps { selected: Date | null; onSelect: (d: Date | null) => void; onClose: () => void; }
function CalendarPopup({ selected, onSelect, onClose }: CalendarPopupProps) {
  const [viewDate, setViewDate] = useState(selected ?? new Date());
  const today = new Date();
  const days = getCalendarDays(viewDate.getFullYear(), viewDate.getMonth());
  return (
    <div className="absolute z-20 bg-white dark:bg-[#242220] border border-gray-200 dark:border-[#34312C] rounded-xl shadow-xl p-3 w-[272px]">
      <div className="flex items-center justify-between mb-2">
        <button type="button" onClick={() => setViewDate(new Date(viewDate.getFullYear(), viewDate.getMonth() - 1, 1))}
          className="p-1 rounded-md border border-gray-200 dark:border-[#34312C] text-gray-500 dark:text-gray-400 hover:bg-gray-50 dark:hover:bg-white/5">
          <CaretLeftIcon size={14} />
        </button>
        <span className="text-sm font-semibold text-gray-800 dark:text-gray-100">{MONTHS_EN[viewDate.getMonth()]} {viewDate.getFullYear()}</span>
        <button type="button" onClick={() => setViewDate(new Date(viewDate.getFullYear(), viewDate.getMonth() + 1, 1))}
          className="p-1 rounded-md border border-gray-200 dark:border-[#34312C] text-gray-500 dark:text-gray-400 hover:bg-gray-50 dark:hover:bg-white/5">
          <CaretRightIcon size={14} />
        </button>
      </div>
      <div className="grid grid-cols-7 mb-1">
        {DAYS_EN.map(d => <div key={d} className="text-center text-[11px] font-medium text-gray-400 dark:text-gray-500 py-1">{d}</div>)}
      </div>
      <div className="grid grid-cols-7 gap-y-1">
        {days.map((d, i) => {
          const inMonth = d.getMonth() === viewDate.getMonth();
          const isSelected = selected ? isSameDay(d, selected) : false;
          const isToday = isSameDay(d, today);
          return (
            <button key={i} type="button" onClick={() => { onSelect(d); onClose(); }}
              className={`mx-auto w-7 h-7 rounded-full text-xs flex items-center justify-center transition-colors ${
                isSelected ? 'bg-amber-600 dark:bg-amber-400 text-white dark:text-[#25211A] font-semibold'
                : isToday ? 'border border-amber-500 dark:border-amber-400 text-amber-600 dark:text-amber-400 font-medium'
                : inMonth ? 'text-gray-700 dark:text-gray-200 hover:bg-gray-100 dark:hover:bg-white/10'
                : 'text-gray-300 dark:text-gray-600 hover:bg-gray-50 dark:hover:bg-white/5'}`}>
              {d.getDate()}
            </button>
          );
        })}
      </div>
      <div className="flex items-center justify-between mt-2 pt-2 border-t border-gray-100 dark:border-white/10">
        <button type="button" onClick={() => { onSelect(null); onClose(); }}
          className="text-xs text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-200">Clear</button>
        <button type="button" onClick={() => { onSelect(today); onClose(); }}
          className="text-xs text-amber-600 dark:text-amber-400 font-medium hover:text-amber-700 dark:hover:text-amber-300">Today</button>
      </div>
    </div>
  );
}

// ─── DatePicker ─────────────────────────────────────────────────────────────────
interface DatePickerProps { label: string; value: Date | null; onChange: (d: Date | null) => void; }
function DatePicker({ label, value, onChange }: DatePickerProps) {
  const [open, setOpen] = useState(false);
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => {
    const h = (e: MouseEvent) => { if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false); };
    document.addEventListener('mousedown', h);
    return () => document.removeEventListener('mousedown', h);
  }, []);
  return (
    <div ref={ref} className="relative">
      <button type="button" onClick={() => setOpen(o => !o)}
        className={`inline-flex items-center justify-between gap-2 min-w-[150px] bg-white dark:bg-[#1e1d1b] border rounded-lg px-3 py-1.5 text-sm outline-none transition-colors ${
          value ? 'border-amber-500 dark:border-amber-400 text-amber-700 dark:text-amber-300'
                : open ? 'border-amber-500 dark:border-amber-400 ring-1 ring-amber-500 dark:ring-amber-400 text-gray-400 dark:text-gray-500'
                : 'border-gray-300 dark:border-[#34312C] text-gray-400 dark:text-gray-500 hover:border-gray-400 dark:hover:border-gray-500'}`}>
        <span className="truncate">{value ? formatDate(getLocalDateString(value)) : label}</span>
        {value ? (
          <XIcon size={14} className="text-amber-600 dark:text-amber-300 hover:text-amber-800 dark:hover:text-amber-100 flex-shrink-0"
            onClick={e => { e.stopPropagation(); onChange(null); }} />
        ) : (
          <CalendarBlankIcon size={14} className="text-gray-400 flex-shrink-0" />
        )}
      </button>
      {open && <CalendarPopup selected={value} onSelect={onChange} onClose={() => setOpen(false)} />}
    </div>
  );
}

// ─── SingleSelectDropdown (one option or cleared — label acts as its own
// placeholder when nothing is selected, matching BRANDING.md §5) ──────────────
interface ToggleOption { value: string; label: string; }
interface SingleSelectDropdownProps { label: string; value: string | null; options: ToggleOption[]; onChange: (v: string | null) => void; align?: 'left' | 'right'; }
function SingleSelectDropdown({ label, value, options, onChange, align = 'left' }: SingleSelectDropdownProps) {
  const [open, setOpen] = useState(false);
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => {
    const h = (e: MouseEvent) => { if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false); };
    document.addEventListener('mousedown', h);
    return () => document.removeEventListener('mousedown', h);
  }, []);
  const current = options.find(o => o.value === value) ?? null;
  const hasValue = !!current;
  return (
    <div ref={ref} className="relative">
      <button type="button" onClick={() => setOpen(o => !o)}
        className={`inline-flex items-center justify-between gap-2 min-w-[170px] bg-white dark:bg-[#242220] border rounded-lg px-3 py-1.5 text-sm outline-none transition-colors ${
          hasValue ? 'border-amber-500 dark:border-amber-400 text-amber-700 dark:text-amber-300'
                   : 'border-gray-300 dark:border-[#34312C] text-gray-400 dark:text-gray-500 hover:border-gray-400 dark:hover:border-gray-500'}`}>
        <span className="truncate">{current ? current.label : label}</span>
        {hasValue ? (
          <XIcon size={14} className="text-amber-600 dark:text-amber-300 hover:text-amber-800 dark:hover:text-amber-100 flex-shrink-0"
            onClick={e => { e.stopPropagation(); onChange(null); }} />
        ) : (
          <CaretDownIcon size={14} className={`text-gray-400 transition-transform flex-shrink-0 ${open ? 'rotate-180' : ''}`} />
        )}
      </button>
      {open && (
        <div className={`absolute top-full ${align === 'right' ? 'right-0' : 'left-0'} mt-1 z-20 bg-white dark:bg-[#242220] border border-gray-200 dark:border-[#34312C] rounded-xl shadow-lg w-[200px] py-1`}>
          {options.map(o => (
            <button key={o.value} type="button" onClick={() => { onChange(o.value); setOpen(false); }}
              className={`w-full text-left px-3 py-1.5 text-sm transition-colors ${
                o.value === value ? 'bg-amber-600 dark:bg-amber-400 text-white dark:text-[#25211A] font-medium'
                                   : 'text-gray-700 dark:text-gray-200 hover:bg-gray-50 dark:hover:bg-white/5'}`}>
              {o.label}
            </button>
          ))}
        </div>
      )}
    </div>
  );
}

// ─── Pill ───────────────────────────────────────────────────────────────────────
function Pill({ children }: { children: React.ReactNode }) {
  return (
    <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-gray-100 dark:bg-white/10 text-gray-600 dark:text-gray-300">
      {children}
    </span>
  );
}
function renderPills(value: string): React.ReactElement {
  const parts = value.split(',').map(s => s.trim()).filter(Boolean);
  if (parts.length === 0) return <span className="text-sm text-gray-400 dark:text-gray-500">—</span>;
  return (
    <div className="flex flex-wrap gap-1">
      {parts.map((p, i) => <Pill key={i}>{p}</Pill>)}
    </div>
  );
}

// ─── Airtable select-color resolution ──────────────────────────────────────────
// All four Airtable intensity tiers (base/Bright/Light1/Light2) resolve to the
// same high-contrast bg-100/text-800 formula per hue, matching this project's
// established pattern (see appointments.tsx) for turning real field-choice
// colors into pill classes instead of a hardcoded per-value map.
const AIRTABLE_COLOR_MAP: Record<string, string> = {
  blue: 'bg-blue-100 dark:bg-blue-900/40 text-blue-800 dark:text-blue-200 border-blue-200 dark:border-blue-700',
  blueBright: 'bg-blue-100 dark:bg-blue-900/40 text-blue-800 dark:text-blue-200 border-blue-200 dark:border-blue-700',
  blueLight1: 'bg-blue-100 dark:bg-blue-900/40 text-blue-800 dark:text-blue-200 border-blue-200 dark:border-blue-700',
  blueLight2: 'bg-blue-100 dark:bg-blue-900/40 text-blue-800 dark:text-blue-200 border-blue-200 dark:border-blue-700',
  cyan: 'bg-cyan-100 dark:bg-cyan-900/40 text-cyan-800 dark:text-cyan-200 border-cyan-200 dark:border-cyan-700',
  cyanBright: 'bg-cyan-100 dark:bg-cyan-900/40 text-cyan-800 dark:text-cyan-200 border-cyan-200 dark:border-cyan-700',
  cyanLight1: 'bg-cyan-100 dark:bg-cyan-900/40 text-cyan-800 dark:text-cyan-200 border-cyan-200 dark:border-cyan-700',
  cyanLight2: 'bg-cyan-100 dark:bg-cyan-900/40 text-cyan-800 dark:text-cyan-200 border-cyan-200 dark:border-cyan-700',
  green: 'bg-green-100 dark:bg-green-900/40 text-green-800 dark:text-green-200 border-green-200 dark:border-green-700',
  greenBright: 'bg-green-100 dark:bg-green-900/40 text-green-800 dark:text-green-200 border-green-200 dark:border-green-700',
  greenLight1: 'bg-green-100 dark:bg-green-900/40 text-green-800 dark:text-green-200 border-green-200 dark:border-green-700',
  greenLight2: 'bg-green-100 dark:bg-green-900/40 text-green-800 dark:text-green-200 border-green-200 dark:border-green-700',
  gray: 'bg-gray-200 dark:bg-white/15 text-gray-800 dark:text-[#F3EFE6] border-gray-300 dark:border-white/15',
  grayBright: 'bg-gray-100 dark:bg-white/10 text-gray-700 dark:text-gray-300 border-gray-200 dark:border-[#38322A]',
  grayLight1: 'bg-gray-100 dark:bg-white/10 text-gray-700 dark:text-gray-300 border-gray-200 dark:border-[#38322A]',
  grayLight2: 'bg-gray-100 dark:bg-white/10 text-gray-700 dark:text-gray-300 border-gray-200 dark:border-[#38322A]',
};
const DEFAULT_STATUS_PILL_CLASSES = 'bg-gray-100 dark:bg-white/10 text-gray-500 dark:text-gray-400 border-gray-200 dark:border-[#38322A]';

// Resolves the actual Airtable option color for a singleSelect field's choices
// so pill colors stay in sync with whatever colors are set on the field in
// Airtable, instead of hardcoding a status→color map (per BRANDING.md §9).
function getFieldChoiceColorMap(field: Field | null | undefined): Map<string, string> {
  const map = new Map<string, string>();
  if (!field) return map;
  const opts = field.options as unknown as { choices?: Array<{ name: string; color?: string }> } | undefined;
  for (const choice of opts?.choices ?? []) {
    if (choice?.name) map.set(choice.name, choice.color ?? '');
  }
  return map;
}

// ─── StatusPillDropdown ─────────────────────────────────────────────────────────
// Clicking the pill opens a small options panel (BRANDING.md §5 dropdown
// pattern — surface/border/shadow, click-outside-to-close) instead of
// toggling the value directly, so the user picks the next status explicitly
// rather than the click silently flipping it to whatever the "other" value
// happens to be.
interface StatusPillDropdownProps {
  value: string | null;
  colorMap: Map<string, string>;
  options: string[];
  onSelect: (next: string) => void;
  disabled?: boolean;
  hasError?: boolean;
}
function StatusPillDropdown({ value, colorMap, options, onSelect, disabled = false, hasError = false }: StatusPillDropdownProps) {
  const [open, setOpen] = useState(false);
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => {
    if (!open) return;
    const h = (e: MouseEvent) => { if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false); };
    document.addEventListener('mousedown', h);
    return () => document.removeEventListener('mousedown', h);
  }, [open]);

  function pillClasses(forValue: string | null): string {
    if (hasError) return 'bg-red-50 dark:bg-red-500/15 text-red-600 dark:text-red-300 border-red-300 dark:border-red-500/40';
    const colorName = forValue ? colorMap.get(forValue) : null;
    return colorName ? (AIRTABLE_COLOR_MAP[colorName] ?? DEFAULT_STATUS_PILL_CLASSES) : DEFAULT_STATUS_PILL_CLASSES;
  }

  return (
    <div ref={ref} className="relative inline-block" onClick={e => e.stopPropagation()}>
      <button type="button" disabled={disabled}
        onClick={() => setOpen(o => !o)}
        className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium border whitespace-nowrap transition-colors ${pillClasses(value)} ${
          disabled ? 'opacity-50 cursor-not-allowed' : 'cursor-pointer hover:brightness-95'}`}>
        {value || '—'}
      </button>
      {open && (
        <div className="absolute left-0 top-full mt-1 z-20 bg-white dark:bg-[#242220] border border-gray-200 dark:border-[#34312C] rounded-xl shadow-lg w-[140px] py-1">
          {options.map(opt => (
            <button key={opt} type="button" onClick={() => { onSelect(opt); setOpen(false); }}
              className={`w-full flex items-center px-3 py-1.5 transition-colors ${
                opt === value ? 'bg-amber-50 dark:bg-amber-500/10' : 'hover:bg-gray-50 dark:hover:bg-white/5'}`}>
              <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium border whitespace-nowrap ${pillClasses(opt)}`}>
                {opt}
              </span>
            </button>
          ))}
        </div>
      )}
    </div>
  );
}

// ─── CommentsCell ───────────────────────────────────────────────────────────────
// Free-text long-text field for Margo to jot name-variation notes for the
// calligraphy card (e.g. nicknames, hyphenation, "goes by middle name"). Local
// state so typing doesn't fight the record's live value on every keystroke;
// only writes on blur, matching the borderless-editable-cell convention
// (BRANDING.md §10b) rather than a boxed input that reads as a separate control.
interface CommentsCellProps {
  value: string;
  disabled: boolean;
  hasError: boolean;
  onSave: (next: string) => void;
}
function CommentsCell({ value, disabled, hasError, onSave }: CommentsCellProps) {
  const [draft, setDraft] = useState(value);
  useEffect(() => { setDraft(value); }, [value]);
  return (
    <textarea
      value={draft}
      disabled={disabled}
      onChange={e => setDraft(e.target.value)}
      onBlur={() => { if (draft !== value) onSave(draft); }}
      placeholder={disabled ? '—' : 'Name variations for the card…'}
      rows={1}
      className={`w-full min-w-[180px] resize-y bg-transparent text-sm text-gray-700 dark:text-gray-300 placeholder-gray-400 dark:placeholder-gray-500 outline-none rounded-md px-1.5 py-1 -mx-1.5 transition-colors ${
        hasError ? 'ring-1 ring-red-400 dark:ring-red-500/60' : 'focus:bg-white dark:focus:bg-[#1e1d1b] focus:ring-1 focus:ring-amber-500 dark:focus:ring-amber-400'} ${
        disabled ? 'opacity-50 cursor-not-allowed' : ''}`}
    />
  );
}

// ─── Custom Properties ──────────────────────────────────────────────────────────
function getCustomProperties(base: ReturnType<typeof useBase>) {
  return [
    {
      key: 'clientsTable', label: 'Clients', type: 'table' as const,
      defaultValue: base.getTableByIdIfExists('tblLLUlDgJ4ktzF7c') ?? base.tables[0],
    },
  ];
}

// ─── CalligraphyCardsApp ────────────────────────────────────────────────────────
function CalligraphyCardsApp(): React.ReactElement {
  useTheme();
  const base = useBase();
  const { customPropertyValueByKey, errorState } = useCustomProperties(getCustomProperties);
  const clientsTable = (customPropertyValueByKey.clientsTable as Table | undefined) ?? null;

  const [calligraphyFilter, setCalligraphyFilter] = useState<string | null>('Pending');
  const [weddingDateFilter, setWeddingDateFilter] = useState<'upcoming' | 'past' | null>('upcoming');
  // Visible filter — default hides clients with a blank Items Sold (no
  // orders at all). Not clearable to "off"; it's always one of these two
  // states, so a plain two-way toggle rather than the clearable
  // SingleSelectDropdown pattern used for the other filters.
  const [itemsSoldFilter, setItemsSoldFilter] = useState<'hideEmpty' | 'showAll'>('hideEmpty');
  const [selectedDueDate, setSelectedDueDate] = useState<Date | null>(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedClientId, setSelectedClientId] = useState<string | null>(null);
  const [updateErrors, setUpdateErrors] = useState<Record<string, boolean>>({});

  const fields = useMemo(() => {
    if (!clientsTable) return {};
    return Object.fromEntries(
      Object.entries(FIELD_IDS).map(([, id]) => [id, clientsTable.getFieldIfExists(id)])
    );
  }, [clientsTable]);

  const allRecords = useRecords(clientsTable ?? null);
  const canWrite = clientsTable ? clientsTable.hasPermissionToUpdateRecords() : false;

  const handleSetCalligraphyCard = useCallback(async (recordId: string, nextValue: string) => {
    const field = fields[FIELD_IDS.CLIENT_CALLIGRAPHY_CARD_SENT];
    if (!clientsTable || !field) return;
    setUpdateErrors(prev => ({ ...prev, [recordId]: false }));
    try {
      await clientsTable.updateRecordAsync(recordId, { [field.id]: { name: nextValue } });
    } catch (err) {
      console.error('Failed to update calligraphy_card_sent', err);
      setUpdateErrors(prev => ({ ...prev, [recordId]: true }));
    }
  }, [clientsTable, fields]);

  const [commentErrors, setCommentErrors] = useState<Record<string, boolean>>({});
  const handleSetComments = useCallback(async (recordId: string, nextValue: string) => {
    const field = fields[FIELD_IDS.CLIENT_CALLIGRAPHY_CARD_COMMENTS];
    if (!clientsTable || !field) return;
    setCommentErrors(prev => ({ ...prev, [recordId]: false }));
    try {
      await clientsTable.updateRecordAsync(recordId, { [field.id]: nextValue || null });
    } catch (err) {
      console.error('Failed to update calligraphy_card_comments', err);
      setCommentErrors(prev => ({ ...prev, [recordId]: true }));
    }
  }, [clientsTable, fields]);

  const searchResults = useMemo(() => {
    if (!allRecords || !searchQuery.trim()) return [];
    const fNameField = fields[FIELD_IDS.CLIENT_FULL_NAME];
    if (!fNameField) return [];
    const q = searchQuery.trim().toLowerCase();
    return allRecords
      .filter(r => (r.getCellValueAsString(fNameField) ?? '').toLowerCase().includes(q))
      .slice(0, 8);
  }, [allRecords, searchQuery, fields]);

  const filteredRecords = useMemo(() => {
    if (!allRecords) return [];
    const fSent = fields[FIELD_IDS.CLIENT_CALLIGRAPHY_CARD_SENT];
    const fWedding = fields[FIELD_IDS.CLIENT_WEDDING_DATE];
    const fDue = fields[FIELD_IDS.CLIENT_DUE_DATE];
    const fName = fields[FIELD_IDS.CLIENT_FULL_NAME];
    const fItemCategory = fields[FIELD_IDS.CLIENT_ITEM_CATEGORY];
    const fItems = fields[FIELD_IDS.CLIENT_ITEMS_SOLD];
    const today = getTodayLocalString();
    const selectedDueStr = selectedDueDate ? getLocalDateString(selectedDueDate) : null;

    let recs = allRecords.filter(rec => {
      // Qualification floor — always applied, not a user-facing filter.
      // Item Category is ALSO a lookup through a link field (shopify_order),
      // same nested-structure quirk as Items Sold/Gown — getCellValueAsString
      // returns blank for it too, so it must go through the same raw-value
      // unwrap as the other two lookup columns, not a plain string read.
      const itemCategoryNames = fItemCategory ? unwrapLinkedNames(rec.getCellValue(fItemCategory)) : [];
      if (!qualifiesNotOnlyShoesOrVeil(itemCategoryNames)) return false;
      // Visible Items Sold filter — replaces the old hard exclusion of
      // empty-category (i.e. no-orders) clients; now the user chooses.
      if (itemsSoldFilter === 'hideEmpty' && fItems) {
        const itemsStr = getLinkedNamesDisplay(rec.getCellValue(fItems));
        if (!itemsStr.trim()) return false;
      }
      if (calligraphyFilter && fSent) {
        const statusName = (rec.getCellValue(fSent) as { name: string } | null)?.name ?? null;
        if (statusName !== calligraphyFilter) return false;
      }
      if (weddingDateFilter && fWedding) {
        const wd = rec.getCellValue(fWedding) as string | null;
        if (!wd) return false;
        const wdLocal = getLocalDateString(new Date(wd));
        if (weddingDateFilter === 'upcoming' && wdLocal < today) return false;
        if (weddingDateFilter === 'past' && wdLocal >= today) return false;
      }
      if (selectedDueStr && fDue) {
        const due = rec.getCellValue(fDue) as string | null;
        if (!due || getLocalDateString(new Date(due)) !== selectedDueStr) return false;
      }
      if (selectedClientId && rec.id !== selectedClientId) return false;
      return true;
    });

    recs = recs.slice().sort((a, b) => {
      const wdA = fWedding ? (a.getCellValue(fWedding) as string | null) : null;
      const wdB = fWedding ? (b.getCellValue(fWedding) as string | null) : null;
      if (wdA && !wdB) return -1;
      if (!wdA && wdB) return 1;
      if (wdA && wdB) {
        const diff = new Date(wdA).getTime() - new Date(wdB).getTime();
        if (diff !== 0) return diff;
      }
      const nameA = fName ? (a.getCellValueAsString(fName) ?? '') : '';
      const nameB = fName ? (b.getCellValueAsString(fName) ?? '') : '';
      return nameA.localeCompare(nameB);
    });

    return recs;
  }, [allRecords, fields, calligraphyFilter, weddingDateFilter, selectedDueDate, selectedClientId, itemsSoldFilter]);

  if (errorState) return (
    <div className="h-screen flex items-center justify-center bg-[#F6F4F0] dark:bg-[#1A1917]">
      <div className="text-center p-8">
        <WarningCircleIcon size={40} className="text-red-500 mx-auto mb-3" />
        <p className="text-sm font-medium text-red-600">Configuration Error</p>
        <p className="text-xs text-gray-500 mt-1">Check the properties panel.</p>
      </div>
    </div>
  );
  if (!clientsTable) return (
    <div className="h-screen flex items-center justify-center bg-[#F6F4F0] dark:bg-[#1A1917]">
      <div className="text-center p-8">
        <p className="text-base font-semibold text-gray-700">Configuration Required</p>
        <p className="text-sm text-gray-500 mt-1">Select the DF Clients table in the properties panel.</p>
      </div>
    </div>
  );

  return (
    <div className="h-screen flex flex-col overflow-hidden antialiased bg-[#F6F4F0] dark:bg-[#1A1917]" style={{ fontFamily: "'Inter', system-ui, sans-serif" }}>
      {/* Header / Filter Bar */}
      <div className="px-6 pt-5 pb-4 flex-shrink-0 flex items-center gap-2">
        <div className="relative flex-1 max-w-[360px]">
          <MagnifyingGlassIcon size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 pointer-events-none" />
          <input type="text" value={searchQuery}
            onChange={e => { setSearchQuery(e.target.value); setSelectedClientId(null); }}
            placeholder="Search by client name…"
            className="w-full pl-9 pr-7 py-1.5 text-sm bg-white dark:bg-[#242220] border border-gray-300 dark:border-[#34312C] rounded-lg text-gray-900 dark:text-gray-100 placeholder-gray-400 dark:placeholder-gray-500 outline-none focus:border-amber-500 dark:focus:border-amber-400 focus:ring-1 focus:ring-amber-500 dark:focus:ring-amber-400 transition-colors" />
          {searchQuery && (
            <button type="button" onClick={() => { setSearchQuery(''); setSelectedClientId(null); }}
              className="absolute right-2 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600 dark:hover:text-gray-200">
              <XIcon size={13} />
            </button>
          )}
          {searchQuery.trim() && !selectedClientId && (
            <div className="absolute top-full left-0 mt-1 z-20 bg-white dark:bg-[#242220] border border-gray-200 dark:border-[#34312C] rounded-xl shadow-lg max-h-[240px] overflow-y-auto w-full py-1">
              {searchResults.length === 0 ? (
                <div className="px-3 py-2 text-sm text-gray-400 dark:text-gray-500">No matches</div>
              ) : searchResults.map(r => (
                <button key={r.id} type="button"
                  onClick={() => { setSelectedClientId(r.id); setSearchQuery(r.getCellValueAsString(fields[FIELD_IDS.CLIENT_FULL_NAME]!) ?? ''); }}
                  className="w-full text-left px-3 py-1.5 text-sm text-gray-700 dark:text-gray-200 hover:bg-gray-50 dark:hover:bg-white/5">
                  {r.getCellValueAsString(fields[FIELD_IDS.CLIENT_FULL_NAME]!) || '—'}
                </button>
              ))}
            </div>
          )}
        </div>
        <DatePicker label="Due Date" value={selectedDueDate} onChange={setSelectedDueDate} />
        <SingleSelectDropdown
          label="Wedding Date"
          value={weddingDateFilter}
          onChange={v => setWeddingDateFilter(v as 'upcoming' | 'past' | null)}
          options={[
            { value: 'upcoming', label: 'Upcoming Wedding Dates' },
            { value: 'past', label: 'Past Wedding Dates' },
          ]}
        />
        <SingleSelectDropdown
          label="Calligraphy Status"
          value={calligraphyFilter}
          onChange={setCalligraphyFilter}
          options={[
            { value: 'Pending', label: 'Pending' },
            { value: 'Sent', label: 'Sent' },
          ]}
          align="right"
        />
        {/* Not a clearable filter (unlike the dropdowns above) — always one of
            two states, so a plain toggle button rather than SingleSelectDropdown. */}
        <button type="button"
          onClick={() => setItemsSoldFilter(f => f === 'hideEmpty' ? 'showAll' : 'hideEmpty')}
          title={itemsSoldFilter === 'hideEmpty' ? 'Clients with blank Items Sold are hidden — click to show them' : 'Showing all clients, including blank Items Sold — click to hide them'}
          className={`inline-flex items-center gap-1.5 px-3 py-1.5 text-sm rounded-lg border transition-colors whitespace-nowrap ${
            itemsSoldFilter === 'hideEmpty'
              ? 'border-amber-500 dark:border-amber-400 text-amber-700 dark:text-amber-300 bg-white dark:bg-[#242220]'
              : 'border-gray-300 dark:border-[#34312C] text-gray-500 dark:text-gray-400 bg-white dark:bg-[#242220] hover:border-gray-400 dark:hover:border-gray-500'}`}>
          {itemsSoldFilter === 'hideEmpty' ? 'Hiding Empty Items Sold' : 'Showing All (Items Sold)'}
        </button>
      </div>

      {/* Table */}
      <div className="flex-1 min-h-0 px-6 pb-4 flex flex-col">
        <div className="bg-white dark:bg-[#242220] border border-[#E5E1DA] dark:border-[#34312C] rounded-xl overflow-hidden flex flex-col flex-1 min-h-0">
          <div className="overflow-y-auto flex-1 overflow-x-auto [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">
            <table className="w-full min-w-[760px] border-collapse">
              <thead className="sticky top-0 z-10 bg-gray-50 dark:bg-[#1e1d1b]">
                <tr className="border-b border-gray-200 dark:border-white/10">
                  <th className="px-3 py-2.5 text-left text-xs font-semibold text-gray-700 dark:text-gray-300 capitalize tracking-wider w-[90px]">Status</th>
                  <th className="px-3 py-2.5 text-left text-xs font-semibold text-gray-700 dark:text-gray-300 capitalize tracking-wider w-[160px]">Client</th>
                  <th className="px-3 py-2.5 text-left text-xs font-semibold text-gray-700 dark:text-gray-300 capitalize tracking-wider w-[200px]">Comments</th>
                  <th className="px-3 py-2.5 text-left text-xs font-semibold text-gray-700 dark:text-gray-300 capitalize tracking-wider w-[120px]">Due Date</th>
                  <th className="px-3 py-2.5 text-left text-xs font-semibold text-gray-700 dark:text-gray-300 capitalize tracking-wider w-[180px]">Items Sold</th>
                  <th className="px-3 py-2.5 text-left text-xs font-semibold text-gray-700 dark:text-gray-300 capitalize tracking-wider w-[160px]">Gown</th>
                  <th className="px-3 py-2.5 text-left text-xs font-semibold text-gray-700 dark:text-gray-300 capitalize tracking-wider w-[100px]">Dress Year</th>
                  <th className="px-3 py-2.5 text-left text-xs font-semibold text-gray-700 dark:text-gray-300 capitalize tracking-wider w-[120px]">Wedding Date</th>
                </tr>
              </thead>
              <tbody>
                {filteredRecords.length === 0 ? (
                  <tr>
                    <td colSpan={8} className="px-3 py-10 text-center text-sm text-gray-400 dark:text-gray-500">No clients match the current filters.</td>
                  </tr>
                ) : filteredRecords.map(rec => {
                  const fName = fields[FIELD_IDS.CLIENT_FULL_NAME];
                  const fDue = fields[FIELD_IDS.CLIENT_DUE_DATE];
                  const fItems = fields[FIELD_IDS.CLIENT_ITEMS_SOLD];
                  const fGown = fields[FIELD_IDS.CLIENT_GOWN_NAME];
                  const fDressYear = fields[FIELD_IDS.CLIENT_DRESS_CREATION_YEAR];
                  const fWedding = fields[FIELD_IDS.CLIENT_WEDDING_DATE];
                  const fSent = fields[FIELD_IDS.CLIENT_CALLIGRAPHY_CARD_SENT];
                  const fComments = fields[FIELD_IDS.CLIENT_CALLIGRAPHY_CARD_COMMENTS];

                  const name = fName ? (rec.getCellValueAsString(fName) ?? '') : '';
                  const commentsStr = fComments ? (rec.getCellValueAsString(fComments) ?? '') : '';
                  const dueStr = fDue ? (rec.getCellValue(fDue) as string | null) : null;
                  const itemsStr = fItems ? getLinkedNamesDisplay(rec.getCellValue(fItems)) : '';
                  const gownStr = fGown ? getLinkedNamesDisplay(rec.getCellValue(fGown)) : '';
                  const dressYearStr = fDressYear ? (rec.getCellValueAsString(fDressYear) ?? '') : '';
                  const weddingStr = fWedding ? (rec.getCellValue(fWedding) as string | null) : null;
                  const statusValue = fSent ? (rec.getCellValue(fSent) as { name: string } | null)?.name ?? null : null;
                  const statusColorMap = getFieldChoiceColorMap(fSent);

                  return (
                    <tr key={rec.id} className="border-b border-gray-100 dark:border-white/5 hover:bg-gray-50 dark:hover:bg-white/5 transition-colors">
                      <td className="px-3 py-2.5">
                        <StatusPillDropdown
                          value={statusValue}
                          colorMap={statusColorMap}
                          options={['Pending', 'Sent']}
                          disabled={!canWrite}
                          hasError={!!updateErrors[rec.id]}
                          onSelect={next => handleSetCalligraphyCard(rec.id, next)}
                        />
                      </td>
                      <td className="px-3 py-2.5 text-sm font-medium text-gray-900 dark:text-[#F5F3EF]">{name || '—'}</td>
                      <td className="px-3 py-2.5">
                        <CommentsCell
                          value={commentsStr}
                          disabled={!canWrite}
                          hasError={!!commentErrors[rec.id]}
                          onSave={next => handleSetComments(rec.id, next)}
                        />
                      </td>
                      <td className="px-3 py-2.5 text-sm text-gray-600 dark:text-gray-300">{formatDate(dueStr)}</td>
                      <td className="px-3 py-2.5">{renderPills(itemsStr)}</td>
                      <td className="px-3 py-2.5">{renderPills(gownStr)}</td>
                      <td className="px-3 py-2.5 text-sm text-gray-600 dark:text-gray-300">{dressYearStr || '—'}</td>
                      <td className="px-3 py-2.5 text-sm text-gray-600 dark:text-gray-300">{formatDate(weddingStr)}</td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
}

initializeBlock({ interface: () => <CalligraphyCardsApp /> });
